// Product Database
const products = [
    {
        id: 1,
        name: 'Pokemon Trading Card Game Box',
        category: 'Sealed Product',
        price: 49.99,
        originalPrice: 59.99,
        discount: -17,
        rating: 4.8,
        reviewCount: 318,
        description: 'A Pokemon TCG display box for collectors and new players building a fresh deck.',
        image: 'image/Pokemon_ Trading Card Game.jpg'
    },
    {
        id: 2,
        name: "Team Rocket's Mewtwo ex",
        category: 'Rare Cards',
        price: 64.99,
        originalPrice: 74.99,
        discount: -13,
        rating: 4.9,
        reviewCount: 142,
        description: 'Double Rare Team Rocket Mewtwo ex from Destined Rivals in collectible condition.',
        image: "image/Pokemon - Team Rocket's Mewtwo ex - 081_182 - Destined Rivals - Double Rare - Single Card.jpg"
    },
    {
        id: 3,
        name: 'Custom Card Maker Print',
        category: 'Custom Cards',
        price: 12.99,
        originalPrice: 12.99,
        rating: 4.4,
        reviewCount: 76,
        description: 'A custom Pokemon-style card print for display, gifting, or binder decoration.',
        image: 'image/PokeCardMaker.jpg'
    },
    {
        id: 4,
        name: 'Collector Pin Card Art',
        category: 'Custom Cards',
        price: 9.99,
        originalPrice: 14.99,
        discount: -33,
        rating: 4.2,
        reviewCount: 54,
        description: 'Decorative Pokemon card artwork inspired by collector pin designs.',
        image: 'image/Pinterest Pin.jpg'
    },
    {
        id: 5,
        name: 'Pikachu Display Art Card',
        category: 'Pikachu Cards',
        price: 18.99,
        originalPrice: 24.99,
        discount: -24,
        rating: 4.7,
        reviewCount: 205,
        description: 'Bright Pikachu display card art for fans completing a themed collection.',
        image: 'image/Pinterest Pin (1).jpg'
    },
    {
        id: 6,
        name: 'Pokemon Collector Art Card',
        category: 'Custom Cards',
        price: 15.99,
        originalPrice: 15.99,
        rating: 4.5,
        reviewCount: 88,
        description: 'Collector-focused Pokemon card artwork with a clean binder-ready look.',
        image: 'image/Pinterest Pin (2).jpg'
    },
    {
        id: 7,
        name: 'Pikachu Pokedex Card',
        category: 'Pikachu Cards',
        price: 21.99,
        originalPrice: 21.99,
        rating: 4.6,
        reviewCount: 167,
        description: 'Pikachu Pokedex-inspired card art for classic electric-type collectors.',
        image: 'image/Pikachu _ Pokédex _ More at Pokemon_com.jpg'
    },
    {
        id: 8,
        name: 'Pikachu VMAX Giant Card',
        category: 'Pikachu Cards',
        price: 39.99,
        originalPrice: 49.99,
        discount: -20,
        rating: 4.8,
        reviewCount: 232,
        description: 'Oversized Pikachu VMAX-style collectible card for display shelves and binders.',
        image: 'image/Pikachu Vmax Giant.jpg'
    },
    {
        id: 9,
        name: 'Pikachu V Promo SWSH061',
        category: 'Pikachu Cards',
        price: 29.99,
        originalPrice: 34.99,
        discount: -14,
        rating: 4.7,
        reviewCount: 190,
        description: 'Pikachu V Sword and Shield promo card for collectors chasing modern favorites.',
        image: 'image/Pikachu V (Sword & Shield Promos SWSH061) (International TCG).jpg'
    },
    {
        id: 10,
        name: 'Pikachu ex Paldea Evolved',
        category: 'Pikachu Cards',
        price: 24.99,
        originalPrice: 29.99,
        discount: -17,
        rating: 4.6,
        reviewCount: 121,
        description: 'Pikachu ex card art from Paldea Evolved for electric-type collections.',
        image: 'image/hello.jpg'
    },
    {
        id: 11,
        name: 'Ultra Instinct Pikachu Custom',
        category: 'Custom Cards',
        price: 17.99,
        originalPrice: 19.99,
        discount: -10,
        rating: 4.3,
        reviewCount: 93,
        description: 'Fan-art crossover custom card featuring a powerful Ultra Instinct Pikachu design.',
        image: 'image/iroltrail.jpg'
    },
    {
        id: 12,
        name: 'Full Art Rayquaza',
        category: 'Rare Cards',
        price: 54.99,
        originalPrice: 69.99,
        discount: -21,
        rating: 4.9,
        reviewCount: 211,
        description: 'Full-art Rayquaza collectible card with bold legendary dragon styling.',
        image: 'image/Full Art 2🌟 _Rayquaza_ (Pokemon Pocket).jpg'
    },
    {
        id: 13,
        name: 'Full Art Alolan Raichu',
        category: 'Rare Cards',
        price: 42.99,
        originalPrice: 52.99,
        discount: -19,
        rating: 4.8,
        reviewCount: 154,
        description: 'Full-art Alolan Raichu card for collectors who like electric-type variants.',
        image: 'image/Full Art 2🌟 _Alolan Raichu_ (Pokemon Pocket).jpg'
    },
    {
        id: 14,
        name: 'Pikachu Novelty Card',
        category: 'Custom Cards',
        price: 7.99,
        originalPrice: 7.99,
        rating: 4.0,
        reviewCount: 48,
        description: 'A playful novelty Pikachu card for casual collecting and display.',
        image: 'image/fake pikachu.jpg'
    },
    {
        id: 15,
        name: 'Amphinobi ex Rainbow Card',
        category: 'Rare Cards',
        price: 34.99,
        originalPrice: 44.99,
        discount: -22,
        rating: 4.7,
        reviewCount: 118,
        description: 'Amphinobi ex rainbow-style card art with a bright water-type action scene.',
        image: 'image/download (4).jpg'
    },
    {
        id: 16,
        name: 'Miraidon ex Gold Card',
        category: 'Rare Cards',
        price: 39.99,
        originalPrice: 49.99,
        discount: -20,
        rating: 4.8,
        reviewCount: 136,
        description: 'Miraidon ex gold-style collectible card with electric legendary artwork.',
        image: 'image/download (5).jpg'
    },
    {
        id: 17,
        name: 'Detective Pikachu GX Custom',
        category: 'Custom Cards',
        price: 16.99,
        originalPrice: 22.99,
        discount: -26,
        rating: 4.5,
        reviewCount: 116,
        description: 'Detective Pikachu GX custom card art with a fan-favorite cinematic theme.',
        image: 'image/Detective Pikachu GX Custom Pokemon Card.jpg'
    },
    {
        id: 18,
        name: 'Crown Rarity Pikachu',
        category: 'Rare Cards',
        price: 74.99,
        originalPrice: 89.99,
        discount: -17,
        rating: 5,
        reviewCount: 97,
        description: 'Premium Crown Rarity Pikachu collectible card for high-value displays.',
        image: 'image/Crown Rarity Pikachu (Pokemon Pocket).jpg'
    },
    {
        id: 19,
        name: 'Charmander Promo 047',
        category: 'Starter Cards',
        price: 19.99,
        originalPrice: 24.99,
        discount: -20,
        rating: 4.6,
        reviewCount: 134,
        description: 'Charmander Scarlet and Violet promo card for fire-type starter fans.',
        image: 'image/Charmander (Scarlet & Violet Promos 047) (International TCG).jpg'
    },
    {
        id: 20,
        name: 'Pokemon Collector Marketplace Poster',
        category: 'Sealed Product',
        price: 8.99,
        originalPrice: 8.99,
        rating: 4.1,
        reviewCount: 39,
        description: 'Marketplace-themed Pokemon collector poster image for store decoration.',
        image: 'image/Your Trusted Marketplace for Collectible Trading Card Games.jpg'
    },
    {
        id: 21,
        name: 'Shadow Venusaur GX Custom',
        category: 'Custom Cards',
        price: 18.99,
        originalPrice: 24.99,
        discount: -24,
        rating: 4.6,
        reviewCount: 83,
        description: 'Shadow Venusaur GX custom card art with bold purple foil-style artwork.',
        image: 'image/download (2).jpg'
    },
    {
        id: 22,
        name: 'Dialga GX Rainbow Card',
        category: 'Rare Cards',
        price: 44.99,
        originalPrice: 54.99,
        discount: -18,
        rating: 4.8,
        reviewCount: 126,
        description: 'Dialga GX rainbow-style collectible card with legendary steel-dragon artwork.',
        image: 'image/download (3).jpg'
    }
];
